Process Process-4:
Traceback (most recent call last):
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "controller.py", line 180, in slave_routine
    r_queue.put((s_id, r_gen.rollout(params)))
  File "controller.py", line 123, in rollout
    self.env.step(action)
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/site-packages/pettingzoo/utils/wrappers/order_enforcing.py", line 68, in step
    super().step(action)
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/site-packages/pettingzoo/utils/wrappers/base.py", line 68, in step
    self.env.step(action)
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/site-packages/pettingzoo/utils/wrappers/assert_out_of_bounds.py", line 24, in step
    super().step(action)
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/site-packages/pettingzoo/utils/wrappers/base.py", line 68, in step
    self.env.step(action)
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/site-packages/pettingzoo/mpe/_mpe_utils/simple_env.py", line 211, in step
    self._execute_world_step()
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/site-packages/pettingzoo/mpe/_mpe_utils/simple_env.py", line 151, in _execute_world_step
    agent_reward = float(self.scenario.reward(agent, self.world))
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/site-packages/pettingzoo/mpe/scenarios/simple_adversary.py", line 83, in reward
    else self.agent_reward(agent, world)
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/site-packages/pettingzoo/mpe/scenarios/simple_adversary.py", line 112, in agent_reward
    for a in good_agents
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/site-packages/pettingzoo/mpe/scenarios/simple_adversary.py", line 112, in <genexpr>
    for a in good_agents
KeyboardInterrupt
