Process Process-8:
Traceback (most recent call last):
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "controller.py", line 189, in slave_routine
    r_queue.put((s_id, r_gen.rollout(params)))
  File "controller.py", line 130, in rollout
    self.env.step(action)
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/site-packages/pettingzoo/utils/wrappers/order_enforcing.py", line 68, in step
    super().step(action)
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/site-packages/pettingzoo/utils/wrappers/base.py", line 68, in step
    self.env.step(action)
  File "/home/jetnew/anaconda3/envs/smawm/lib/python3.6/site-packages/pettingzoo/utils/wrappers/assert_out_of_bounds.py", line 21, in step
    ) or self.action_spaces[self.agent_selection].contains(
KeyboardInterrupt
